### ISSUE TITLE
ERC1155 pending tasks

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-contracts#2230]
This issue tracks the tasks pending for the ERC1155 feature to be complete and releasable.

- [x] Improve extensibility of ERC1155 (#2003)
- [x] Port to Solidity v0.6
- [x] Re-review the code, mostly for security issues.
- [x] Add more tests, increase test coverage.
- [x] Compare with [Augur's implementation](https://github.com/AugurProject/augur/blob/master/packages/augur-core/source/contracts/libraries/token/ERC1155.sol).
- [x] Review URI support. (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2029)
- [x] Hook (single flavor using arrays)
- [x] Pausable
- [x] Burnable (single & batched)
- [x] Preset (MinterPauser)
- [x] Review revert reasons
- [x] Documentation (API, and mention in tokens guide)

**Comment by AC0DEM0NK3Y** [comment]
Forgive if I'm wrong it's been a while since I looked at a node but afaik you do not need an archive node to pull history of events you only need an archive node to pull historical state.

**Comment by JosephBagaric** [comment]
@nventuro would it be possible to add ERC1155 support to https://github.com/OpenZeppelin/openzeppelin-contracts-ethereum-package?

Seems like it would be an easy port. I can even port it if necessary.

**Comment by nventuro** [comment]
Hello @JosephBagaric! Thank you for bringing this up.

Yes, it will be included in that package as well. We'll port it ourselves once the code is finished - we use an automated tool for this task to reduce the chance of human errors when migrating constructors.
