### ISSUE TITLE
Test migration tracking

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4658]
## List of files to migrate:

- [x] `test/access/AccessControl.behavior.js` #4694
- [x] `test/access/AccessControl.test.js` #4694
- [x] `test/access/extensions/AccessControlDefaultAdminRules.test.js` #4694
- [x] `test/access/extensions/AccessControlEnumerable.test.js` #4694
- [x] `test/access/manager/AccessManaged.test.js` #4710
- [x] `test/access/manager/AccessManager.behavior.js` #4710
- [x] `test/access/manager/AccessManager.test.js` #4710
- [x] `test/access/manager/AuthorityUtils.test.js` #4710
- [x] `test/access/Ownable2Step.test.js`: #4657 
- [x] `test/access/Ownable.test.js`: #4657 #4710
- [x] `test/finance/VestingWallet.behavior.js` #4723
- [x] `test/finance/VestingWallet.test.js` #4723
- [x] `test/governance/extensions/GovernorERC721.test.js` #4728
- [x] `test/governance/extensions/GovernorPreventLateQuorum.test.js` #4728
- [x] `test/governance/extensions/GovernorStorage.test.js` #4728
- [x] `test/governance/extensions/GovernorTimelockAccess.test.js` #4728
- [x] `test/governance/extensions/GovernorTimelockCompound.test.js` #4728
- [x] `test/governance/extensions/GovernorTimelockControl.test.js` #4728
- [x] `test/governance/extensions/GovernorVotesQuorumFraction.test.js` #4728
- [x] `test/governance/extensions/GovernorWithParams.test.js` #4750
- [x] `test/governance/Governor.test.js` #4728 #4750
- [x] `test/governance/TimelockController.test.js` #4728
- [x] `test/governance/utils/EIP6372.behavior.js` #4728
- [x] `test/governance/utils/Votes.behavior.js` #4750 #4728
- [x] `test/governance/utils/Votes.test.js` #4728
- [x] `test/helpers/access-manager.js` #4710
- [x] `test/helpers/account.js` #4732 #4737 #4746
- [ ] `test/helpers/chainid.js`
- [x] `test/helpers/constants.js` #4710 #4797
- [x] `test/helpers/create.js`: #4689
- [ ] `test/helpers/customError.js`: **deprecated**
- [ ] `test/helpers/deploy.js`
- [x] `test/helpers/eip712.js`: #4689 #4749 #4750
- [ ] `test/helpers/enums.js` #4728#4797
- [x] `test/helpers/erc1967.js`: #4689 #4746
- [x] `test/helpers/governance.js` #4728
- [ ] `test/helpers/iterate.js`
- [x] `test/helpers/namespaced-storage.js` #4710
- [x] `test/helpers/math.js` #4737 #4732
- [x] `test/helpers/methods.js`: #4689
- [x] `test/helpers/sign.js` #4749
- [ ] `test/helpers/time.js` #4728 #4773#4797
- [x] `test/helpers/txpool.js` #4728
- [x] `test/metatx/ERC2771Context.test.js` #4732 #4737
- [x] `test/metatx/ERC2771Forwarder.test.js` #4732 #4737
- [x] `test/proxy/beacon/BeaconProxy.test.js` #4746
- [x] `test/proxy/beacon/UpgradeableBeacon.test.js` #4746
- [x] `test/proxy/Clones.behaviour.js` #4746
- [x] `test/proxy/Clones.test.js` #4746
- [x] `test/proxy/ERC1967/ERC1967Proxy.test.js` #4746
- [x] `test/proxy/ERC1967/ERC1967Utils.test.js` #4746
- [x] `test/proxy/Proxy.behaviour.js` #4746
- [x] `test/proxy/transparent/ProxyAdmin.test.js` #4746
- [x] `test/proxy/transparent/TransparentUpgradeableProxy.behaviour.js` #4746
- [x] `test/proxy/transparent/TransparentUpgradeableProxy.test.js` #4746
- [x] `test/proxy/utils/Initializable.test.js` #4746
- [x] `test/proxy/utils/UUPSUpgradeable.test.js` #4746
- [x] `test/token/common/ERC2981.behavior.js` #4793
- [x] `test/token/ERC1155/ERC1155.behavior.js` #4771
- [x] `test/token/ERC1155/ERC1155.test.js` #4771
- [x] `test/token/ERC1155/extensions/ERC1155Burnable.test.js` #4771
- [x] `test/token/ERC1155/extensions/ERC1155Pausable.test.js` #4771
- [x] `test/token/ERC1155/extensions/ERC1155Supply.test.js` #4771
- [x] `test/token/ERC1155/extensions/ERC1155URIStorage.test.js` #4771
- [x] `test/token/ERC1155/utils/ERC1155Holder.test.js` #4771
- [x] `test/token/ERC20/ERC20.behavior.js` #4743
- [x] `test/token/ERC20/ERC20.test.js` #4743
- [x] `test/token/ERC20/extensions/ERC20Burnable.behavior.js` #4773
- [x] `test/token/ERC20/extensions/ERC20Burnable.test.js` #4773
- [x] `test/token/ERC20/extensions/ERC20Capped.behavior.js` #4773
- [x] `test/token/ERC20/extensions/ERC20Capped.test.js` #4773
- [x] `test/token/ERC20/extensions/ERC20FlashMint.test.js` #4773
- [x] `test/token/ERC20/extensions/ERC20Pausable.test.js` #4773
- [x] `test/token/ERC20/extensions/ERC20Permit.test.js` #4750 #4773
- [x] `test/token/ERC20/extensions/ERC20Votes.test.js` #4750 #4728
- [x] `test/token/ERC20/extensions/ERC20Wrapper.test.js` #4773
- [x] `test/token/ERC20/extensions/ERC4626.test.js` #4773
- [x] `test/token/ERC20/utils/SafeERC20.test.js` #4773
- [x] `test/token/ERC721/ERC721.behavior.js` #4793
- [x] `test/token/ERC721/ERC721Enumerable.test.js` #4793
- [x] `test/token/ERC721/ERC721.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721Burnable.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721Consecutive.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721Pausable.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721Royalty.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721URIStorage.test.js` #4793
- [x] `test/token/ERC721/extensions/ERC721Votes.test.js` #4728
- [x] `test/token/ERC721/extensions/ERC721Wrapper.test.js` #4793
- [x] `test/token/ERC721/utils/ERC721Holder.test.js` #4793
- [x] `test/utils/Address.test.js` #4743 #4739
- [x] `test/utils/Arrays.test.js` #4736
- [x] `test/utils/Base64.test.js` #4736
- [x] `test/utils/Context.behavior.js` #4732 #4737
- [x] `test/utils/Context.test.js` #4732 #4737
- [x] `test/utils/Create2.test.js` #4736
- [x] `test/utils/cryptography/ECDSA.test.js` #4749
- [x] `test/utils/cryptography/EIP712.test.js` #4749 #4750
- [x] `test/utils/cryptography/MerkleProof.test.js`: #4689
- [x] `test/utils/cryptography/MessageHashUtils.test.js` #4749
- [x] `test/utils/cryptography/SignatureChecker.test.js` #4749
- [x] `test/utils/introspection/ERC165Checker.test.js` #4794
- [x] `test/utils/introspection/ERC165.test.js` #4794
- [x] `test/utils/introspection/SupportsInterface.behavior.js` #4694
- [x] `test/utils/math/Math.test.js` #4769
- [x] `test/utils/math/SafeCast.test.js` #4769
- [x] `test/utils/math/SignedMath.test.js` #4769
- [x] `test/utils/Multicall.test.js` #4736
- [x] `test/utils/Nonces.test.js` #4736
- [x] `test/utils/Pausable.test.js` #4736
- [x] `test/utils/ReentrancyGuard.test.js` #4736
- [x] `test/utils/ShortStrings.test.js` #4736
- [x] `test/utils/StorageSlot.test.js` #4736
- [x] `test/utils/Strings.test.js` #4736
- [x] `test/utils/structs/BitMap.test.js` #4748
- [x] `test/utils/structs/Checkpoints.test.js` #4748
- [x] `test/utils/structs/DoubleEndedQueue.test.js` #4748
- [x] `test/utils/structs/EnumerableMap.behavior.js` #4748
- [x] `test/utils/structs/EnumerableMap.test.js` #4748
- [x] `test/utils/structs/EnumerableSet.behavior.js` #4748
- [x] `test/utils/structs/EnumerableSet.test.js` #4748
- [x] `test/utils/types/Time.test.js` #4778

## List of related migrations

- [ ] Remove dependencies we don't directly need such as `ethereumjs` in favor of `ethers`'s alternatives

**Comment by ernestognw** [comment]
We're adding custom behaviors to support both Truffle and Ethers while we're migrating. A couple of those things to consider are when finishing the migration are:

- Remove all the `DEPRECATE` annotations for packages we still need
- Remove high-level snapshot introduced in #4652 in favor of `loadFixture` (if AccessManager doesn't consume the `block.timestamp` as we initially thought)
- We'll need to support both ethers's `signers` and Truffle `accounts` in [this line](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f92dce51ed24a5b4e0009c1522ee12b30f3409ac/hardhat/env-contract.js#L22). We should remove `accounts` support eventually
