### ISSUE TITLE
abstract contract ERC721URIStorage is ERC721 {     using Strings for uint256;      // Optional mapping for token URIs     mapping(uint256 => string) internal _tokenURIs; ...

### ISSUE THREAD

**Issue by vit870** [OpenZeppelin/openzeppelin-contracts#5202]
**🧐 Motivation**

**📝 Details**

```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5166
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5201
```

```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5200
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5201
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5199
```
