### ISSUE TITLE
[Meta] Account abstraction tracking

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#5245]
# 5.2
- #5242
- #5243
- #5244
- #5250
- #5274
- resolve a few pending question:
  - `ERC4337Utils.sol`
    - `combineValidationData`: keep it? For what usecase? what if `aggregator1 == aggregator2`
    - `getValidationData`: "in range" vs "out of range" boolean
  
# Next

- Track ERC-7739 changes
- Account framework into `openzeppelin-community-contracts`

# Later
- [ ] #5246
  - should not be packaged, can be removed from files exception
  - need to fix linter
  - alternative, put these files into a dependency that we import
    - that would be cleaner for upgradeability
  - because `vendor/erc4337-entrypoint` is not package, moving it or removing it would not be breaking
- [ ] When hardhat fixes https://github.com/NomicFoundation/hardhat/issues/4399
  - revert `OZ Edit` in `contracts/vendor/erc4337-entrypoint/core/EntryPoint.sol`
  - remove the `upgradable.exclude.patch` for the transpilation process

**Comment by Amxx** [comment]
# Features

- [x] Entrypoint: `@openzeppelin/contracts/vendor` (mocks? other repo?)
- [x] ERC4337 interface: `@openzeppelin/contracts/interface`
- [x] ERC7579 interface: `@openzeppelin/contracts/interface`
- [x] ERC4337 utils: `@openzeppelin/contracts/account/utils`
- [x] ERC7579 utils: `@openzeppelin/contracts/account/utils`
- [ ] ERC7739 utils: `@openzeppelin/contracts/utils/cryptography` (community?)
- [ ] ERC7739 signer: `@openzeppelin/contracts/utils/cryptography` (community?)
- [ ] AccountBase: `@openzeppelin/community-contracts/account` ?
- [ ] AccountECDSA, AccountP256, AccountRSA: `@openzeppelin/community-contracts/account/extensions` ?
- [ ] AccountERC7579, AccountERC7579Hooks: `@openzeppelin/community-contracts/account/extensions` ?
- [ ] ERC7579Modules: `@openzeppelin/community-contracts/account/modules`
- [ ] Factory: `@openzeppelin/contracts/mocks` ?

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
