### ISSUE TITLE
blockchain smart contract for web3

### ISSUE THREAD

**Issue by 383093** [OpenZeppelin/openzeppelin-contracts#5249]
**🧐 Motivation**

**📝 Details**

```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5243
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5242
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5248
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5192
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5245
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5235
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5247
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3802
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5238
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5233
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5246
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5236
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5189
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5182
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5244
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5239
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5240
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4957
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5241
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5237
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4971
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5013
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5124
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5029
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5011
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4647
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5035
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5131
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5139
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5130
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5217
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5234
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5229
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5097
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5230
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5218
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5232
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5220
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4660
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5214
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5210
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5228
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3604
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5231
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5208
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5103
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5227
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4821
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5225
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5177
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5223
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5222
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5221
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5148
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5224
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5206
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5216
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/issues/5197
- [ ] https://github.com/OpenZeppelin/openzeppelin-contracts/pull/5211
```

**Comment by 383093** [comment]
[CCU delivery - Wikipedia.pdf](https://github.com/user-attachments/files/17334969/CCU.delivery.-.Wikipedia.pdf)
[Method engineering - Wikipedia.pdf](https://github.com/user-attachments/files/17334970/Method.engineering.-.Wikipedia.pdf)
[Systems development life cycle - Wikipedia.pdf](https://github.com/user-attachments/files/17334971/Systems.development.life.cycle.-.Wikipedia.pdf)
